# Generated by Django 5.1 on 2024-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
