# Generated by Django 5.1 on 2024-08-13 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_game_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameround",
            old_name="player_bets",
            new_name="game_state",
        ),
        migrations.RemoveField(
            model_name="gameround",
            name="community_cards",
        ),
        migrations.RemoveField(
            model_name="gameround",
            name="dealer_hand",
        ),
        migrations.RemoveField(
            model_name="gameround",
            name="player_hands",
        ),
    ]
